"""add jobs table

Revision ID: a05d81b3c859
Revises: edebb0209dbf
Create Date: 2026-01-19 22:05:55.700202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05d81b3c859'
down_revision: Union[str, Sequence[str], None] = 'edebb0209dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PRELABEL', 'EXPORT', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('agent_mode', sa.Boolean(), nullable=True),
    sa.Column('plan_v0_json', sa.JSON(), nullable=True),
    sa.Column('sample_metrics_json', sa.JSON(), nullable=True),
    sa.Column('plan_v1_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
